'use strict';

// ============================================================================
// Offboarding PDF forms (pdfkit): the Employee Exit Interview Form and the
// Employee Exit Clearance Form, laid out after the WCT paper forms (and
// Qurratu's prototype). ONE drawing function per form, used for both the
// download endpoints and the payroll email attachments, so the two can
// never drift apart.
//
// Both take a case bundle from lifecycle.loadBundle() and resolve a Buffer.
// ============================================================================

const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');
const { EXIT_REASONS } = require('./constants');

const LOGO = path.join(__dirname, '..', '..', '..', 'assets', 'wct-logo.png');
const LEFT = 50;
const WIDTH = 495;
const BOTTOM = 790;
const BAR = '#D9E4EE';

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
function fmt(v) {
  if (!v) return '';
  const s = typeof v === 'string' ? v.slice(0, 10) : new Date(v).toISOString().slice(0, 10);
  return `${Number(s.slice(8, 10))} ${MONTHS[Number(s.slice(5, 7)) - 1]} ${s.slice(0, 4)}`;
}
function fmtDateTime(v) {
  if (!v) return '';
  const d = new Date(v);
  const myt = new Date(d.getTime() + 8 * 3600000);
  return `${fmt(myt.toISOString())} ${myt.toISOString().slice(11, 16)}`;
}

function render(draw) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50, bufferPages: true });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    try {
      draw(doc);
      // Footer with page numbers on every page.
      const range = doc.bufferedPageRange();
      for (let i = range.start; i < range.start + range.count; i += 1) {
        doc.switchToPage(i);
        // Writing below the bottom margin would make pdfkit start a new
        // (blank) page, so drop the margin just for the footer line.
        doc.page.margins.bottom = 0;
        doc.font('Helvetica').fontSize(7).fillColor('#6E6E6D')
          .text(`Generated by the WCT HR system · Page ${i + 1} of ${range.count}`, LEFT, 810, { width: WIDTH, align: 'center', lineBreak: false });
      }
      doc.fillColor('#000000');
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

/** Tiny layout helper around a pdfkit doc with a moving y cursor. */
function writer(doc) {
  const w = {
    y: 50,
    ensure(h) { if (w.y + h > BOTTOM) { doc.addPage(); w.y = 50; } },
    header(title, subtitle, ref) {
      if (fs.existsSync(LOGO)) doc.image(LOGO, LEFT, w.y, { width: 55 });
      doc.font('Helvetica-Bold').fontSize(8).fillColor('#000').text('PRIVATE & CONFIDENTIAL', 395, w.y, { width: 150, align: 'right' });
      doc.font('Helvetica').fontSize(8).text(ref || '', 395, w.y + 11, { width: 150, align: 'right' });
      doc.font('Helvetica-Bold').fontSize(15).text(title, 115, w.y + 12, { width: 290 });
      if (subtitle) doc.font('Helvetica-Oblique').fontSize(7).text(subtitle, 115, w.y + 32, { width: 430 });
      w.y += 68;
    },
    bar(label) {
      w.ensure(40);
      doc.rect(LEFT, w.y, WIDTH, 16).fill(BAR);
      doc.fillColor('#000').font('Helvetica-Bold').fontSize(9).text(label, LEFT + 4, w.y + 4, { width: WIDTH - 8 });
      w.y += 24;
    },
    field(x, label, value, labelW, lineW) {
      doc.font('Helvetica-Bold').fontSize(8).text(label, x, w.y, { width: labelW });
      const sx = x + labelW + 2;
      doc.moveTo(sx, w.y + 10).lineTo(sx + lineW, w.y + 10).lineWidth(0.5).stroke();
      doc.font('Helvetica').fontSize(8).text(value || '', sx + 2, w.y, { width: lineW - 4, height: 10, ellipsis: true });
    },
    pair(l1, v1, l2, v2) {
      w.ensure(20);
      w.field(LEFT, l1, v1, 105, 140);
      w.field(305, l2, v2, 70, 170);
      w.y += 18;
    },
    checkbox(x, label, checked, width = 200) {
      doc.rect(x, w.y, 9, 9).lineWidth(0.7).stroke();
      if (checked) {
        doc.moveTo(x + 1.5, w.y + 4.5).lineTo(x + 3.8, w.y + 7.3).lineTo(x + 7.8, w.y + 1.8).lineWidth(1.2).stroke();
      }
      doc.font('Helvetica').fontSize(8).text(label, x + 15, w.y + 0.5, { width });
    },
    para(text, opts = {}) {
      const h = doc.font(opts.font || 'Helvetica').fontSize(opts.size || 8).heightOfString(text || '', { width: opts.width || WIDTH - 8 });
      w.ensure(h + 6);
      doc.text(text || '', opts.x || LEFT + 4, w.y, { width: opts.width || WIDTH - 8 });
      w.y += h + (opts.gap == null ? 6 : opts.gap);
    },
  };
  return w;
}

function exitInterviewPdf(bundle) {
  const c = bundle.case;
  const ei = bundle.exitInterview || {};
  const chosen = new Set(Array.isArray(ei.reasons) ? ei.reasons : []);
  const others = Array.isArray(ei.reasons_other) ? ei.reasons_other.filter(Boolean) : [];

  return render((doc) => {
    const w = writer(doc);
    w.header('EMPLOYEE EXIT INTERVIEW FORM', null, c.ref_no);

    w.bar('A: EMPLOYEE DETAILS');
    w.pair('Name (as per NRIC):', c.employee_name, 'Position:', c.position);
    w.pair('Immediate Superior:', c.immediate_superior_name, 'Dept/Site:', c.department);
    w.pair('Date Joined:', fmt(c.date_joined), 'Notice Period:', c.notice_period_days != null ? `${c.notice_period_days} days` : '');
    w.pair('Official Last Day:', fmt(c.official_last_day), 'Actual Last Day:', fmt(c.actual_last_day));
    w.pair('Company:', c.company_name, 'Business Unit:', c.business_unit);
    w.y += 8;

    w.bar('B: PLEASE INDICATE REASON(S) BELOW, WHICH CONTRIBUTED TO YOUR DECISION TO RESIGN');
    // Two columns in the paper form's reading order (reasons 1,3,5.. left).
    for (let i = 0; i < EXIT_REASONS.length; i += 2) {
      w.ensure(18);
      const rowY = w.y;
      w.checkbox(LEFT + 4, EXIT_REASONS[i], chosen.has(EXIT_REASONS[i]));
      w.y = rowY;
      w.checkbox(305, EXIT_REASONS[i + 1], chosen.has(EXIT_REASONS[i + 1]));
      w.y = rowY + 17;
    }
    w.ensure(18);
    w.checkbox(LEFT + 4, 'Others, please specify:', others.length > 0);
    w.y += 15;
    others.forEach((t, i) => w.para(`${i + 1}. ${t}`, { x: LEFT + 20, width: WIDTH - 24, gap: 3 }));
    w.y += 8;

    w.bar("C: EMPLOYEE'S COMMENT(S) / SUGGESTIONS FOR IMPROVEMENT(S)");
    w.para(ei.comments || '—', { gap: 14 });
    w.ensure(40);
    doc.font('Helvetica').fontSize(9).text('Employee Signature:', LEFT + 4, w.y);
    doc.font('Helvetica-Oblique').fontSize(13).text(ei.employee_signature_name || '....................................', 150, w.y - 3, { width: 160 });
    doc.font('Helvetica').fontSize(9).text(`Date: ${ei.employee_signed_at ? fmtDateTime(ei.employee_signed_at) : '—'}`, 330, w.y, { width: 210 });
    w.y += 20;
    doc.font('Helvetica').fontSize(7).fillColor('#6E6E6D')
      .text('Signed electronically by typing their name after signing in with the email address the invitation was sent to.', LEFT + 4, w.y, { width: WIDTH - 8 });
    doc.fillColor('#000');
    w.y += 22;

    w.bar('D: FOR HRD (HQ) USE ONLY - TO BE COMPLETED BY HR PERSONNEL');
    if (ei.hr_comments) w.para(`Comments: ${ei.hr_comments}`, { gap: 8 });
    w.ensure(50);
    doc.font('Helvetica').fontSize(9);
    doc.text('Signature:', LEFT + 4, w.y);
    doc.font('Helvetica-Oblique').fontSize(12).text(ei.hr_signed_name || '....................................', 110, w.y - 2, { width: 180 });
    doc.font('Helvetica').fontSize(9).text(`Name in Full: ${ei.hr_signed_name || '....................................'}`, 300, w.y, { width: 245 });
    w.y += 22;
    doc.text(`Position: ${ei.hr_signed_position || '....................................'}`, LEFT + 4, w.y, { width: 240 });
    doc.text(`Date: ${ei.hr_signed_at ? fmtDateTime(ei.hr_signed_at) : '....................................'}`, 300, w.y, { width: 245 });
    w.y += 20;
  });
}

function clearancePdf(bundle) {
  const c = bundle.case;
  return render((doc) => {
    const w = writer(doc);
    w.header('EMPLOYEE EXIT CLEARANCE FORM',
      'Kindly complete this form and ensure all sections have been verified and signed by the respective Unit Heads before submission to HR & Admin Dept for processing.',
      c.ref_no);

    w.pair('Name (as per NRIC):', c.employee_name, 'Position:', c.position);
    w.pair('Dept/Site:', c.department, 'Business Unit:', c.business_unit);
    w.pair('Date Joined:', fmt(c.date_joined), 'Last Working Day:', fmt(c.actual_last_day || c.official_last_day));
    w.y += 8;

    bundle.sections.forEach((s, idx) => {
      const letter = String.fromCharCode(65 + idx);
      w.bar(`${letter}: ${s.department_name}${s.status === "complete" ? "" : "  (pending)"}`);
      // Column headings
      doc.font('Helvetica-Bold').fontSize(7.5).text('Item', LEFT + 20, w.y).text('Remarks', 330, w.y);
      w.y += 12;
      s.items.forEach((it) => {
        const label = it.is_other ? `Others${it.custom_text ? `: ${it.custom_text}` : ''}` : it.item_text;
        if (it.is_other && !it.custom_text && !it.is_checked && !it.remarks) return; // unused "Others" slot
        const h = Math.max(
          doc.font('Helvetica').fontSize(8).heightOfString(label, { width: 280 }),
          doc.heightOfString(it.remarks || '', { width: 210 })
        );
        w.ensure(h + 6);
        const rowY = w.y;
        w.checkbox(LEFT + 4, label, it.is_checked, 260);
        doc.font('Helvetica').fontSize(8).text(it.remarks || '', 330, rowY + 0.5, { width: 210 });
        w.y = rowY + h + 5;
      });
      w.ensure(28);
      w.y += 4;
      doc.font('Helvetica').fontSize(8.5).text('Signed by:', LEFT + 4, w.y);
      doc.font('Helvetica-Oblique').fontSize(11).text(s.signed_by_name || '....................................', 100, w.y - 2, { width: 170 });
      doc.font('Helvetica').fontSize(8.5).text(
        `${s.signed_by_email ? `(${s.signed_by_email})` : ''}${s.signed_on_behalf ? ' on behalf, by HR' : ''}`,
        275, w.y, { width: 150 }
      );
      doc.text(`Date: ${s.signed_at ? fmtDateTime(s.signed_at) : '—'}`, 430, w.y, { width: 115 });
      w.y += 24;
    });

    w.bar('EMPLOYEE ACKNOWLEDGEMENT');
    w.para('I acknowledge that I have returned all company property and settled all matters listed above, and that the information in this form is accurate.', { gap: 10 });
    w.ensure(30);
    doc.font('Helvetica').fontSize(9).text('Employee Signature:', LEFT + 4, w.y);
    doc.font('Helvetica-Oblique').fontSize(13).text(c.acknowledged_signature_name || '....................................', 150, w.y - 3, { width: 170 });
    doc.font('Helvetica').fontSize(9).text(
      c.acknowledged_at ? `Acknowledged: ${fmtDateTime(c.acknowledged_at)}` : 'Not yet acknowledged',
      330, w.y, { width: 215 }
    );
    w.y += 26;
    if (c.payroll_completed_at) {
      w.bar('PAYROLL');
      w.para(`Payroll completed on ${fmtDateTime(c.payroll_completed_at)} by ${c.payroll_completed_by_email || ''}${c.payroll_remarks ? ` — ${c.payroll_remarks}` : ''}`);
    }
  });
}

module.exports = { exitInterviewPdf, clearancePdf };
